# Generated by Django 5.1 on 2024-08-29 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0002_post_subject_bid_resource_post_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 'Learner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'type': 'Tutor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Tutor', 'Tutor'), ('Learner', 'Learner')], default='Tutor', max_length=20),
        ),
    ]
