# Generated by Django 5.1 on 2024-09-14 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0004_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'type': 'Tutor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(limit_choices_to={'type': 'Tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to=settings.AUTH_USER_MODEL)),
                ('origin', models.ForeignKey(limit_choices_to={'type': 'Learner'}, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
