# Generated by Django 5.1 on 2024-09-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0005_alter_resource_tutor_escrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
