# Generated by Django 5.1 on 2024-10-04 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0006_escrow_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('has_external_resources', models.BooleanField(default=False)),
                ('lessons_needed', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(limit_choices_to={'type': 'Tutor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.subject')),
            ],
        ),
        migrations.CreateModel(
            name='classReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('reviewer', models.ForeignKey(limit_choices_to={'type': 'Learner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.learningclass')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_seats', models.IntegerField(default=10)),
                ('class_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('lesson_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.learningclass')),
            ],
        ),
    ]
