# Generated by Django 5.1 on 2024-10-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0007_learningclass_classreview_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningclass',
            name='description',
            field=models.TextField(default='this is a sample description for the existing records'),
            preserve_default=False,
        ),
    ]
